name: Bug Report
description: Report unexpected behavior, errors, or defects
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thank you for submitting a bug report! Please fill out the following details as thoroughly as possible to help us understand and resolve the issue.

  - type: textarea
    id: problem-description
    attributes:
      label: Problem Description
      description: Please describe the problem in as much detail as possible.
      placeholder: Describe the problem here... when pasting error logs, please use markdown code blocks.
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        If the problem is not reproducible consistently, please set "Settings - Command Prompt - Debug - Show Detailed Logs and Debug Information" to 0. Also, please monitor the Console logs in the Developer Tools (Settings - Apps - Enable Developer Tools), and upload a screenshot of the console log when you encounter the issue.

  - type: textarea
    id: reproduce-steps
    attributes:
      label: Reproduction Steps
      description: Describe the steps or settings needed to reproduce the issue. If the problem is not consistently reproducible, please note the frequency and upload any error messages.
      placeholder: |
        1. Step one
        2. Step two
        3. Step three
    validations:
      required: true

  - type: textarea
    id: screenshots-or-recordings
    attributes:
      label: Screenshots or Recordings
      description: (Optional) Please upload screenshots or recordings to demonstrate the issue and reproduction steps.
      placeholder: Upload screenshots or recordings here...

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: (Optional) Describe what you expect the plugin to do or how it should behave.
      placeholder: Describe the expected behavior here...

  - type: textarea
    attributes:
      label: Device and System Information
      description: |
        Example:
          - **Operating System**: Windows 11 24H2
          - **Tabby**: v1.0.215
      value: |
          - Operating System:
          - Tabby:
      render: markdown
    validations:
      required: true

  - type: checkboxes
    id: check_list
    attributes:
      label: Check list
      description: Please confirm the following things before raising an issue.
      options:
      - label: I have checked the issue list and believe no one has reported a similar issue
        required: true
      - label: I have updated the plugin to the latest version
        required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: (Optional) If you have any additional related information, please provide it here.
      placeholder: Provide additional information here...
